/*SELECT: serve para projetar na tela, os campos especificados da consulta ao banco de dados, não tem nada haver com selecionar.
*/
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
WHERE sexo = 'F';

/*Para fazer uma junção de tabelas ligadas é usado o INNER JOIN, exemplo:*/

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';

/*Como juntar mais de uma tabela, 1 pra muitos, utilizando o ponto.*/

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/*Como juntar mais de uma tabela, 1 pra muitos, utilizando o ponto.
2° FORMA:*/

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/* INSERT */
INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '989238928');
INSERT INTO ENDERECO VALUES(NULL, 'RUA JOAQUIM', 'ALVORADA', 'NITEROI', 'RJ', 7);

SELECT * FROM CLIENTE;

/* FILTROS */
SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL, 'XXX', 'M', NULL, 'XXXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;

/* DDL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */
/* CHANGE É MAIS INDICADO PARA TROCAR NOME DA COLUNA*/

ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

/* MODIFY - ALTERANDO TIPO - MODIFY É MAIS INDICADO PARA MODIFICAR TIPO*/

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO UMA COLUNA */

ALTER TABLE PRODUTO
DROP COLUMN PESO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA */
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

/*USANDO O FIRST PARA ADICIONAR POR PRIMEIRO*/

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;

/* COMO EXIBIR DADOS DE 3 TABELAS AO MESMO TEMPO */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
        E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

/* 12, 13, 18, 19*/
SELECT * FROM CLIENTE
WHERE IDCLIENTE = 12
OR IDCLIENTE = 13
OR IDCLIENTE = 18
OR IDCLIENTE = 19;

/* MANEIRA MAIS ADEQUADA UTILIZANDO O IN()*/

SELECT * FROM CLIENTE
WHERE IDCLIENTE IN(12,13,18,19);

/* RELATORIO DE MULHERES */
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
        E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'

/* COMO ATUALIZAR INFORMAÇÃO DO SEXO DO CLIENTE DE ID 16 */
UPDATE CLIENTE SET SEXO = 'M'
WHERE IDCLIENTE = 16; 

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE
GROUP BY SEXO; 

/* IDS E EMAILS DAS MULHERES QUE MOREM NO CENTRO DO 
RIO DE JANEIRO E NÃO TENHAM CELULAR*/

SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
AND (TIPO = 'RES' OR TIPO = 'COM');

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO
COM O NOME, EMAIL E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO
DE JANEIRO, VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA
O PROGRAMADOR
*/ 

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR /*PROJEÇÃO*/
FROM CLIENTE C /*ORIGEM*/
INNER JOIN ENDERECO E /*JUNÇÃO*/
ON C.IDCLIENTE = E.ID_CLIENTE /*JUNÇÃO CONDIÇÃO*/
INNER JOIN TELEFONE T /*JUNÇÃO*/
ON C.IDCLIENTE = T.ID_CLIENTE /*JUNÇÃO CONDIÇÃO*/ 
WHERE TIPO = 'CEL' AND ESTADO = 'SP'; /*SELEÇÃO*/
/*TABELA DE ORIGEM SEMPRE É A QUE POSSUE MAIS JUNÇÃO*/

/*-----------------------------------------------------*/

/*PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU
UM RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR DAS MULHERES QUE MORAM
NO ESTADO DE SÃO PAULO, VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR P RELATÓRIO
PARA O PROGRAMAROR
*/
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F'
AND ESTADO = 'SP';

/* TRATAR A APRESENTAÇÃO DOS VALORES NULL*/
SELECT C.NOME, IFNULL(C.EMAIL,'NÃO TEM EMAIL') AS "EMAIL",
E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;